### ISSUE TITLE
Screenbloom crashing on Win 10 1909

### ISSUE THREAD

**Issue by qserror** [kershner/screenBloom#100]
Hey @kershner  how are you?

Since a couple of days this error shows up after login in windows... even i try to start screenbloom manually its the same error showing up...
![grafik](https://user-images.githubusercontent.com/35936407/77364252-71ac0200-6d54-11ea-912c-92dd6feb309a.png)

its possible that ubiquiti network devices call this error?

best regards!

V.

**Comment by Huskynarr** [comment]
He didt find the correct IP. Try Reinstall. ;)

**Comment by qserror** [comment]
> 
> 
> He didt find the correct IP. Try Reinstall. ;)
ooops! you're right! now it works properly! Nice :D
