### ISSUE TITLE
username and password required at first run

### ISSUE THREAD

**Issue by adibendahan** [kershner/screenBloom#11]
Hi,
I've just installed the latest version (on Windows 10) and when trying to run the app for the first time I get a prompt to enter username and password (for the http://10.0.0.2:5000/new-user URL),

No matter what I do nothing works, no idea what the user/pass are since it's the first run and I've never set it...

Any ideas?

**Comment by kershner** [comment]
Any chance you could post a screenshot?  ScreenBloom does not require any usernames / passwords.

**Comment by adibendahan** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/2807536/18187142/c8b5f3c6-70af-11e6-9064-001cd78ae465.png)

**Comment by kershner** [comment]
Yeah I would look into your networking setup.  That looks like some kind of address/port collision.  Maybe there is another service running on that address/port that does require a password?  As I said before ScreenBloom does not require any kind of a password.

I will be closing this issue now, but please let me know if you find anything out.  Good luck.

**Comment by adibendahan** [comment]
Well, a Plex server is installed. Looks like they can't work together.

**Comment by adibendahan** [comment]
turned out to be [Shairport4w](http://www.lightweightdream.com/sp4w/shairport4w/?lang=en).

**Comment by kershner** [comment]
Good to know, I'll try to cook up some port collision handling in a future version.

One thing you could try as a temporary workaround is start the Shairport4w app **after** you have the ScreenBloom server running.  That program might have port collision detection and will just run on a different one if ScreenBloom is already using :5000.
