### ISSUE TITLE
Startup fails (ImportError: DLL load failed)

### ISSUE THREAD

**Issue by s-hutter** [kershner/screenBloom#12]
Hi there :)

I wanted to try ScreenBloom on Windows (10, 64bit) today, but can't get it to start. The console window immediately closes. Running screenbloom.exe from command line reveals the following error message:

`C:\Program Files (x86)\ScreenBloom>screenbloom.exe
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "ScreenBloom.py", line 2, in <module>
  File "c:\programming\projects\hue_project\app\modules\screenbloom_functions.py", line 20, in <module>
    from desktopmagic.screengrab_win32 import getDisplaysAsImages
  File "c:\python27\lib\site-packages\desktopmagic\screengrab_win32.py", line 9, in <module>
ImportError: DLL load failed: The application has failed to start because its side-by-side configuration is incorrect. Please see the application event log or use the command-line sxstrace.exe tool for more detail.
`

Any idea how to fix this?

**Comment by kershner** [comment]
Yeah I get a few reports like this.  The DLLs should be included in the ScreenBloom install but I don't know why they're not being registered.

Some people have reported installing Visual Studio will get all the DLLs registered.  Let me know if it works for you.

**Comment by joshfedo** [comment]
Im on a clean install of windows 10 home and im getting 
C:\Program Files (x86)\ScreenBloom>screenbloom sxstrace.exe
Traceback (most recent call last):
```
  File "c:\python27\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "ScreenBloom.py", line 2, in <module>
  File "c:\programming\projects\hue_project\app\modules\screenbloom_functions.py", line 20, in <module>
    from desktopmagic.screengrab_win32 import getDisplaysAsImages
  File "c:\python27\lib\site-packages\desktopmagic\screengrab_win32.py", line 9, in <module>
ImportError: DLL load failed: The application has failed to start because its side-by-side configuration is incorrect. Please see the application event log or use the command-line sxstrace.exe tool for more detail.
```

I just installed visual studios and rebooted but its still not wokring for me either.

**Comment by s-hutter** [comment]
It's working for me after installing [Visual Studio 2008 Express Edition with SP1](http://stackoverflow.com/a/37018436) - the link kershner posted is just a PowerPoint file and when you install the latest 2015 Visual Studio it won't work. You should try installing the 2008 version. (I chose the Visual C++ option for the installation, not sure if the others work as well.)

**Comment by kershner** [comment]
I think I know what the problem is - my installer script (Inno) isn't registering the DLLs.  I'm messing with it now but am not having a lot of luck.  The best scenario seems to be installing VS 2008 to get all the dlls you need.  This link should get you what you want:
https://www.microsoft.com/en-us/download/details.aspx?id=10986

I'll edit my post above as well

**Comment by joshfedo** [comment]
Yup that did it. I installed VS studios 2015 and it didn't work but after installing 2008 it worked.

**Comment by kershner** [comment]
Sweet, glad to have a solution that works for now.  I'll put something up on the website guiding people to the Visual Studio download while I try to get the install script DLL registration working.  Thanks for all the info, **joshfedo** and **s-hutter**.
