### ISSUE TITLE
Cant Run on. Possibly some python issue on my end.

### ISSUE THREAD

**Issue by hipstersmoothie** [kershner/screenBloom#17]
i get this when i run ./screenBloom from the command line

Traceback (most recent call last):
  File "<string>", line 355, in <module>
socket.gaierror: [Errno 8] nodename nor servname provided, or not known
screenbloom returned -1

**Comment by kershner** [comment]
Thanks for reporting this.  I've gotten a handful of reports about this error (on the Mac version, correct)?  It has something to do with not being able to find your machine's IP, I believe.  I currently don't know what is causing the error because I can't reproduce it on my Mac.  I will keep trying to solve it.

**Comment by hipstersmoothie** [comment]
Yeah I'm on a macOS Sierra. if there is anything else i can do to help you. just holler away

**Comment by kershner** [comment]
If you have the time can you let me know what these commands output?  Open up a Python shell and do the following:
```
import socket
print socket.gethostbyname(socket.getfqdn())  # Let me know what this outputs
print socket.gethostbyname(socket.gethostname())  # This should produce the error
```
I appreciate it!

**Comment by hipstersmoothie** [comment]
```
>>> import socket
>>> print socket.gethostbyname(socket.getfqdn())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
socket.gaierror: [Errno 8] nodename nor servname provided, or not known
>>> print socket.gethostbyname(socket.gethostname())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
socket.gaierror: [Errno 8] nodename nor servname provided, or not known
>>>
```

some extra 

```
>>> print socket.getfqdn()
Andrews-MacBook-Pro.local
>>> print socket.gethostname()
Andrews-MacBook-Pro.local
>>>
```

**Comment by kershner** [comment]
Can you try this one?  I think this is the winner:
```
import socket
s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
s.connect(("8.8.8.8", 80))
print(s.getsockname()[0])
s.close()
```

**Comment by hipstersmoothie** [comment]
```
>>> s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
>>> s.connect(("8.8.8.8", 80))
>>> print(s.getsockname()[0])
192.168.0.15
>>> s.close()
```

**Comment by kershner** [comment]
Just beautiful.  I've had a few other confirmations that this code produces the right IP, from people who also got the socket.gaierror before.  I'm going to do some more testing with it and probably put it into the next version, which should be ready pretty soon.

Thanks so much for your help!

**Comment by hipstersmoothie** [comment]
Awesome! Glad i could help. 

Btw I got it working on my work computer, and a I have some gen 3 lights. They program doesnt really produce the full spectrum the new lights can produce. Specifically bringing up a blue or green screen produces gen2 looking color.

**Comment by kershner** [comment]
Interesting, can you send a link or a screen of the image that produces the color?

**Comment by hipstersmoothie** [comment]
example for green

**Comment by hipstersmoothie** [comment]
Light blue comes out purple: 

image used:
data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAARwAAACxCAMAAAAh3/JWAAAAA1BMVEUekP/tgdY3AAAASElEQVR4nO3BMQEAAADCoPVPbQ0PoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIALA8UNAAFusnLHAAAAAElFTkSuQmCC

**Comment by kershner** [comment]
Thanks for the info.  The ScreenBloom parsing algorithm came up with [this color](http://www.colorhexa.com/1e90ff) for that image, so I think it's just the RGB->Hue conversion.  The library I use is pretty old so the gamuts could be out of wack with the new Hue stuff.  I'll look into getting it updated, and I should probably get some new Hue stuff for testing (a convenient excuse to get new Hue shit haha).
