### ISSUE TITLE
Won't detect lightstrip

### ISSUE THREAD

**Issue by RobErskine** [kershner/screenBloom#19]
I just picked up a [Phillips Hue Light Strip ](http://www2.meethue.com/en-us/productdetail/philips-hue-lightstrip) and ScreenBloom doesn't seem to be picking it up. Of course, this is under the "bulbs" section, so I realize the lightstrip isn't a bulb, so maybe it's intentional, but I just wanted to make sure I wasn't missing anything on my end. 

It detects my 3 bulbs from my starter kit, but not my lightstrip. Was hoping to wrap the lightstrip around my desk for some additional fun lighting, but doesn't seem to want to pick it up.

**Comment by kershner** [comment]
Hey there,

I think you just need to re-gen your config file to pick up the new bulbs (strips in your case).  There is a small icon in the bottom right of the page that will walk you through re-generating your config file.

Lemme know if you run into any trouble!

**Comment by RobErskine** [comment]
Good call. I had no idea that button was there :O. Could we add a section to the FAQs for adding new bulbs? Happy to do that

**Comment by kershner** [comment]
Haha yeah that button needs to be re-thought.  It's too invisible.  Good call on an Adding Bulbs section in the FAQ, I will definitely do that.

Thanks for your patience!

**Comment by RobErskine** [comment]
Thanks for building this awesome piece of software. I use it everyday.
