### ISSUE TITLE
Connect to hue bridge by IP

### ISSUE THREAD

**Issue by ankushg** [kershner/screenBloom#2]
Many networks (especially those in college campuses) only allow users to connect to Hue bridges and other devices by IP. It would be really awesome if there was an option to manually specify your bridge's IP address while setting up.

**Comment by kershner** [comment]
Hey Ankush,

There actually is a way to manually specify your IP - just point your
browser to */manual* instead of */new-user*.  There should have been a
prompt if it failed to register the first time, that might be broken!  I'll
look into it.

Thanks for the email.

**Comment by ankushg** [comment]
Ah, manually visiting the URL did the trick. Maybe I just didn't wait long enough in the normal onboarding process :)

**Comment by kershner** [comment]
Great! Glad it's working for you.

**Comment by kershner** [comment]
Your friend, Tyler has invited you to try Cratejoy's all-in-one subscription business platform.

Join hundreds of successful merchants who make a living doing what they love.

Start your Free Trial at: https://my.cratejoy.com/v/register/Qk0LPAIn?utm_source=spreadlove&amp;utm_medium=email&amp;utm_campaign=trial_extend
