### ISSUE TITLE
Feature: Music visualizer

### ISSUE THREAD

**Issue by Kakifrucht** [kershner/screenBloom#21]
Screenbloom would listen to music output and change the lights to sync up to the music.

Amazing program! Thanks alot.

**Comment by kershner** [comment]
Hey there, thanks for the feedback.  This kind of thing has been brought up before and I agree it's a really cool idea, but I think it's beyond the scope of ScreenBloom.  You'd need to add another program's worth of functionality and at that point, why not just make the other program?

Have you checked out this program?
## [Ambify](http://getambify.com/mac.html)

**Comment by Kakifrucht** [comment]
That looks good, if it wasn't MacOS only...

**Comment by saschb2b** [comment]
Check out http://www.huegasm.com/ for selected tracks. Does the job quite well on a party. But I have to agree that this is out of scope for this project.

**Comment by Kakifrucht** [comment]
Looks good. I am thinking about writing an open source solution myself that listens to audio streams.

**Comment by Kakifrucht** [comment]
Uploaded my take on music visualization for free to [GitHub](https://github.com/Kakifrucht/LightBeat).

**Comment by kershner** [comment]
That is amazing, really great job.  Can't wait to try this out.
