### ISSUE TITLE
Cant find new Lights

### ISSUE THREAD

**Issue by eff3s** [kershner/screenBloom#23]
When i first started up Screenbloom, i had only one lightstrip installed.
After some time I installed a second one, however I can not find the new lightstrip in the Screenbloom interface.
edit: all lights are visible in the philips hue app

**Comment by kershner** [comment]
Thanks for bringing this up, you're not the first to be confused by it!  I'll eventually either handle new lights automatically or put some kind of info about the procedure in the website F.A.Q.

**Comment by brodyhoskins** [comment]
Hello, what is the solution for finding new bulbs?

**Comment by kershner** [comment]
Just gotta re-generate your config file.  Hit the button in the top right of the page and click 'Regen Config File' or something like that.
