### ISSUE TITLE
ScreenBloom 1.2 after config migration

### ISSUE THREAD

**Issue by Kakifrucht** [kershner/screenBloom#24]
Very stoked for this update. Following stacktrace prevents the program from starting. It did run once before though. I would just try around and refresh my config, my bridge isn't in the same room as I am though so it would be annoying.

````
---------------------------
cx_Freeze: Python error in main script
---------------------------
Traceback (most recent call last):
  File "c:\programming\projects\hue_project\venv\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "ScreenBloom.py", line 437, in <module>
  File "c:\programming\projects\hue_project\app\modules\startup.py", line 42, in run
  File "c:\programming\projects\hue_project\app\modules\startup.py", line 88, in start_server
  File "C:\Python27\Lib\webbrowser.py", line 61, in open
  File "C:\Python27\Lib\webbrowser.py", line 543, in open
TypeError: coercing to Unicode: need string or buffer, NoneType found
````

Very minor issue: The taskbar icon gets stuck upon shutting down, until passing your mouse cursor. I guess it needs to be refreshed?

**Comment by kershner** [comment]
So the program won't launch now after trying the 2.2 update?  But it did run once?  I wonder if there is a caching issue?  Did you install over the top of the previous version, and if so maybe try a full uninstall / reinstall to see if there is a change.

And yeah the taskbar thing is funny.  Clicking the 'Quit' option calls a very abrupt os-level exit() function, but I can probably make some kind of call to refresh/remove the icon before that happens.  Thanks for pointing it out :)

**Comment by Kakifrucht** [comment]
I uninstalled everything and reinstalled, once again first run works after relinking the bridge. When I restart the app I get the same issue.

**Comment by kershner** [comment]
Ok so lemme know if this is the correct chain of events for you:

1. Uninstall ScreenBloom v2.1, download/install v2.2
2. Load up ScreenBloom, it probably says something like 'your config needs to be updated', you click the button to regen the config / re-start the registration process
3. You register with the bridge and a new config file is created, everything works just fine.
4. You quit / restart the app, and you get the error message you posted above

Is that about right?  How exactly is the error message being displayed to you, curious as the Python console has been removed.

**Comment by Kakifrucht** [comment]
Exactly, it is shown in a little windows error panel.

**Comment by kershner** [comment]
Hmm this is an odd one but it kinda reminds me of something I was experiencing during development.

This will sound weird but can you try opening it a bunch of times?  Like, it'll crash 4 times in a row but then maybe the 5th time it'll work.  At least that's something I experienced the other day.  

By the way, what's your CPU?

**Comment by Kakifrucht** [comment]
Seems to crash every time.
I have an Intel i7 4790.

**Comment by kershner** [comment]
Ok, cooked up a possible fix, can you give this one a try and let me know if the issue is solved?  Thanks again for helping me test!

[](http://www.kershner.org/static/distribute/screenBloom_2.2_win.zip)

**Comment by Kakifrucht** [comment]
It's fixed, thanks!

**Comment by kershner** [comment]
![Shocked Michael Scott](http://www.vomzi.com/wp-content/uploads/2016/02/cute-nice-gif-143.gif)
Nice!

Thanks again for raising the issue.
