### ISSUE TITLE
Feature: Starting and Ending States

### ISSUE THREAD

**Issue by TwanoO67** [kershner/screenBloom#3]
Hi Tyler,

I'm trying to implement some new features on your app, but I'm still learning python so maybe someone will be quicker than me. So I'm just dropping the idea here:

It would be nice to have a Starting State and a Ending State to send to the bulbs, on start and stop of the app.

Example, in my setup, it would be cool to have a starting state that will put "on" the selected bulbs.
(for the moment the app doesn't switch the lights on, so I have to set it with another app)
And for the exit state: I will set a selected color and put 'off' the lights.
( I have my restroom lights on white with a dimming switch (that can't change colors), then I used it for screenbloom, but after that I have to manually set the color to white with my phone because the diming switch can't change back the color)

**Comment by kershner** [comment]
So the app includes a button to turn the selected lights on/off, as well as a default color option that the lights will return to when ScreenBloom is stopped.  Are you suggesting a feature where this will be done automatically for the selected lights?

I.E. you select some lights from the list and click 'Start'.  If the lights are currently off, they will be turned on.  When you click 'Stop' the lights will be returned to your selected default color (this currently happens) and additionally be turned off.

Or is it more that you want to be able to choose a default color for individual bulbs?

**Comment by TwanoO67** [comment]
Ok! My bad! 
The grey button "Turn Lights off" made me think it was disactivated.
And for the "default color" I was thinking that this was a color that will be send when the picture has too many dark zone. 
So my settings was to set that into a dark color, so my room will have very few light during darker scene.
And it seems to work quite good, but then I had not the right color when exiting the app.

So there's apparently no new feature here ^^ I was just miss using it, sorry.
But for my understanding, is the "default color" really working as a sort of "threshold color" for too dark scene? Or was it just my mind playing some tricks ?
And if so, would it be possible to separate the "Threshold color" from the "Exit color" values ?

**Comment by kershner** [comment]
No worries, the app could probably some documentation haha.  One day.

I wonder if you're thinking about [this](https://github.com/kershner/screenBloom/blob/master/app/modules/screenbloom_functions.py#L362) **threshold**?  I've definitely thought about making that a user-tweakable setting, but I'm still not sure.  It just sets a limit to how dark a pixel can be and still be counted toward the average color of the scene.  It's meant to weed out totally black pixels that would wash out the computed color average if left in.

In any case, the default color setting is just a color you can pick that the lights will return to when you stop the ScreenBloom process.  Often ScreenBloom will put your lights into a really dark or weird color state, so I find it's nice to be able to return them to a normal color when you're done.

**Comment by TwanoO67** [comment]
Ok, thanks for the explanations :)
The threshold you pointed was the one I talked about, and I understand it better now.

So, there's no new feature to do here... issue can be closed :)
