### ISSUE TITLE
With bulbs that aren't Hue?

### ISSUE THREAD

**Issue by DylanAlloy** [kershner/screenBloom#30]
If I wanted to use this with some other wifi LED bulb, would it work? Not familiar with the Hue API but it's just a packet sent over wifi in the end, right?

**Comment by kershner** [comment]
Nah I can't see it working as is.  

ScreenBloom can only address bulbs that are enumerated by the Hue bridge, so you would need the third party WiFi bulb to be fully discoverable by the bridge.  And even if they were discoverable, they'd need to have attributes that the Hue bridge can interact with like values for brightness, color, etc.  The attribute names would need to match up with what the Hue API is expecting, which I wouldn't count on.

Your best bet would be to just use bits and pieces of ScreenBloom's code (like the [image average function here](https://github.com/kershner/screenBloom/blob/master/app/modules/img_proc.py#L17)) and integrate it into your own code for interfacing with the lights.

**Comment by meyerrj** [comment]
I know this is old, but there is a workaround that might help people out.

If you're using [Home Assistant](https://www.home-assistant.io/), you can install the Emulated Hue add-on: https://www.home-assistant.io/integrations/emulated_hue/ 

I've been using this and it works great with some Philips WiZ lights. :)
