### ISSUE TITLE
install - reboot - bloom crashes

### ISSUE THREAD

**Issue by Uncle808** [kershner/screenBloom#31]
All I'm doing is running the application, shutting down the pc (maybe without shutting down the exe), and this appears when I run it the next time the PC is used:

![screenbloom_cxfreeze](https://cloud.githubusercontent.com/assets/17384738/24336295/c5ae2a3e-128c-11e7-9c47-908c02a3526e.jpg)

**Comment by kershner** [comment]
Hey there.

Two things I can think of for this one:

1.  You're upgrading from a previous version and Windows is giving you a hard time about cached registry entries.  Uninstall ScreenBloom, reboot your PC, and then reinstall 2.2.
2. Your config file is corrupt.  Either re-generate it from a page on ScreenBloom (if you can access any), or manually delete it and re-open ScreenBloom.  

It's located in
`c:/Users/Username/AppData*/Roaming/screenBloom/screenbloom_config.cfg`

*You'll need to enable 'Show Hidden Files' to see this directory.

**Comment by Uncle808** [comment]
trick: start > run or win key + r on keyboard (both open the run dialog) and **%APPDATA%** will open the roaming subfolder of appdata.
my prefered way since I move the users & documents folders to D:\ (saved my ass several times already, once when a seagate HDD crashed from simply shutting down the pc).

Will try a fresh install today.

**Comment by Uncle808** [comment]
forced clean installation. seems to be resolved now.

**Comment by kershner** [comment]
Glad to hear it!
