### ISSUE TITLE
Screen Zones

### ISSUE THREAD

**Issue by Dangerously** [kershner/screenBloom#33]
2.2 screen zones stopped working. On Windows 10, FireFox, IE 11, Edge, all do not work. Generate new config file also does not work in any browser (elevated/admin or not). Party mode is the only feature that works.
2.1 works just fine.

**Comment by kershner** [comment]
Hi there, thanks for bringing this up.

This is a known issue, see #20 .  Currently working on a fix,

**Comment by Dangerously** [comment]
Issue #20 does not look like my issue. I do not get a "devide by 0" error.
I get no errors.
When a screen zone is turned on (doesn't matter how the zones are created),
the lights will come on to the default colour and stay there. They will
never change no matter what is on screen. No errors or no incorrect text
that I can see in the .cfg.
2.2 will only change colour when in party mode. Went back to 2.1 all is
working fine.
I have attached my config file for you to see.

**Comment by kershner** [comment]
Yep, it's the same issue.  I just hastily added some handling in the last update to not crash the program when it happens.  So it'll just display a neutral color or something when it's happening.  I just need to find some time to really dig into it to find out what's happening.

For the record the bug only happens in Zone mode.  You won't get the bug in any of the other modes like normal or party mode.

**Comment by kershner** [comment]
Also if you could take note of what type of image on your screen produces the error, that'd be really great for me to check out on my own PC for debugging.

**Comment by itroy187** [comment]
Hey there. I'd like to use three screen zones (with three hue Blooms) with version 2.2, but it doesn't work. Only one lamp works and the other two just stay at a blueish color. As soon as I turn screen zone mode off, everything all three lamps work fine.

While testing, I've noticed something funny: One of my other hue light bulbs, which not even is active in screen bloom, starts blinking in different colors, when I start screen zone mode.

Tried resetting everything (config, uninstall etc.), but nothing helps. With version 2.1 I have no such problems btw. Seems to be a bug introduced in 2.2.

Config is attached.
[screenBloom_config.zip](https://github.com/kershner/screenBloom/files/1253975/screenBloom_config.zip)

**Comment by kershner** [comment]
Hey hey, thanks for the detailed writeup.  

Everything you're reporting sounds similar to what others have experienced regarding this issue, so I think I should be able to narrow it down.  I'm currently fixing a few bugs so I'm going to dive into this one today.  I'll let you know if I need any more info from you.

Thanks again for reaching out!

**Comment by kershner** [comment]
I just pushed up what I think might be a fix for the issue.  Can you grab a fresh copy from [www.screenbloom.com](www.screenbloom.com), reinstall and let me know if the problem has been resolved?

**Comment by itroy187** [comment]
Hey, it's working! I'm glad I could help narrowing down the problem.

I guess it's movie time then ;)

**Comment by kershner** [comment]
Really appreciate the help, was a simple thing that was tough for me to replicate on my own setup.

Let me know if you ever run into any more issues.
