### ISSUE TITLE
Feature: Default Color for windows

### ISSUE THREAD

**Issue by Uncle808** [kershner/screenBloom#36]
Would be nice if I could select a default color for windows unless an application goes fullscreen, probably not feasible, though.
Also, separate brightness for applications. I'll try the last with saved presets, but that feels a bit clunky.

**Comment by kershner** [comment]
I used to have a default color option that you could set the Hues to return to when you clicked 'Stop ScreenBloom.'  Sometime later a user asked if it'd be possible for the Hues to just return to their initial color before ScreenBloom was started.  That idea was great and pretty much made the Default Color option redundant.  It simplified the application which is always good.

As far as different settings for different games, yeah I think the Presets feature covers this use case pretty well.  It is indeed a bit clunky (like the whole program lol), but I think having a separate menu or something for per-game settings would be just as clunky, not to mention raise the complexity of the app by quite a bit.

Thanks for bringing it up, and I'd love to hear from you if you have any further ideas about the subject.  For now I think the use case is pretty well covered.
