### ISSUE TITLE
Error at startup

### ISSUE THREAD

**Issue by s5zone** [kershner/screenBloom#38]
![image](https://cloud.githubusercontent.com/assets/25084905/25558024/945b4e56-2d1e-11e7-85ec-138c63dd7123.png)

It used to work until some days ago, just out of nowhere I got this. I installed nothing that should cause this.

**Comment by kershner** [comment]
Hey there,

Looks like a pretty standard connection error.  Either to the small ScreenBloom web server or to your Hue bridge.  Has anything big or small changed about your network setup recently?  This error looks like it's specifically having trouble reaching your Hue bridge.

**Comment by s5zone** [comment]
Webserver does not seem to start. I can easily control my hue lamps with any other application on my phone

**Comment by kershner** [comment]
I would definitely try a fresh install of ScreenBloom.  There really shouldn't be any reason for it to just up and stop working - unless maybe your Hue bridge IP changed and the config file needs to be updated.

Try a full, clean install:
1. Uninstall ScreenBloom
2. Reboot PC
3. Reinstall ScreenBloom 2.2

**Comment by s5zone** [comment]
Hello again,

Thanks for the tip about the IP change. I did have to reboot my router in the last couple of days.
As expected, the IP changed. I now gave the bridge a fixed IP, updated the screenbloom config and tada! Everything works again.

Thanks again for the quick help! Keep up the great work!!

**Comment by kershner** [comment]
Awesome, glad to hear that everything is working again.  Just let me know if you run into any further issues!
