### ISSUE TITLE
Choose Display Screens appearing black

### ISSUE THREAD

**Issue by zaughon** [kershner/screenBloom#45]
Hey.
I was playing around with this, but i can't get it to do anything. 
When i set it up, both screens appear black: 
![chrome_2017-07-08_15-44-30](https://user-images.githubusercontent.com/13797858/27985880-a963f5e8-63f4-11e7-97e3-d01ecd8bb5d3.png)
when i start it, both lights go to a white-ish light, and never change, no matter what kind of color is on the screen. It looks like the application for some reason can't see any content on my screens. 

Is there any work around for this? I've tried changing the compatibility options as mentioned on the site, but it didn't change anything. I don't have the "Disable display scaling on high DPI settings"-option though.  All i have is "Override high DPI scaling behavior. Scaling performed by: 
Application
System
System (Enhanced)"
Or: "Disable fullscreen optimizations"

Windows 10
GFX: Nvidia GeForce GTX 980 Ti
Monitor 1: AOC AG271QG4
Monitor 2: BenQ RL2450H
They're connected with either HDMI or DisplayPort. Might be 1 of each.

**Comment by kershner** [comment]
Hey zaughton,

This happens because of an anti-virus program blocking ScreenBloom from accessing the Windows screen capture functionality.  Simply whitelist ScreenBloom in your antivirus of choice, or disable entirely, and you should be good to go!

Let me know how it works out for you.

**Comment by zaughon** [comment]
Ah, of course. That fixed it. Thanks! :)
