### ISSUE TITLE
Compatibilty with LEDs with open http APIs

### ISSUE THREAD

**Issue by ageorgios** [kershner/screenBloom#48]
There are so many other colorful led lights other than philips (yeelight, ailight, itead led light, h801 with sonoff-tasmota firmware and so on) with open http apis

It would be really great if there was a way to integrate with these other leds

I would recommend a generic set of actions in screenBloom like:
setPower(on/off)
setColor(HEX)
where everyone could configure the http requests required for each action

and a way to disable philips hue modules if they are not needed

**Comment by kershner** [comment]
This is a really cool idea but I simply don't have the time/resources to develop it.  I'm fully available to help get it off the ground and answer any questions about the code though.  Hit me up anytime.

**Comment by lcorsini** [comment]
I could try to have a look, owning both Hue (bulb) and a Yeelight strip behind the monitor, I'm interested in this project

**Comment by lcorsini** [comment]
there is a yeelight python library, so it could be easier than tought https://yeelight.readthedocs.io/en/latest/

**Comment by BnMcG** [comment]
I'm looking at adding YeeLight support myself, if I can get it working I'll submit a PR.
