### ISSUE TITLE
Screen zones 4K support

### ISSUE THREAD

**Issue by RoyboyNL** [kershner/screenBloom#52]
It seems that only the upper-left part of my 4k display can be used to select screen zones and display its colors.
![zones](https://user-images.githubusercontent.com/5683136/31853912-2b34315c-b691-11e7-80a4-b58fd1b6d08d.png)

Thanks for making such beautiful app!

**Comment by kershner** [comment]
Hey there!  This is a known quirk in one of ScreenBloom's dependencies.  Pretty easy fix, though.

You just need to check Disable display scaling on high DPI settings in the ScreenBloom executable's compatibility settings. 

Right click on screenbloom.exe, click properties, and find the Compatibility tab.

Here's a handy image.
![ScreenBloom High DPI Scaling Fix](http://www.screenbloom.com/static/images/display_scaling_tutorial.png)

Lemme know if that fixes the issue for you.

**Comment by RoyboyNL** [comment]
Thanks for your quick response, very helpful and fixed it instantly!
