### ISSUE TITLE
Error 500 - global name 'img_proc' is not defined

### ISSUE THREAD

**Issue by mihai7785** [kershner/screenBloom#56]
Hello,
I just installed the app but I receive this error on startup (after registration). Can you please help me?
Txs!

**Comment by kershner** [comment]
Hey there - this is typically caused by a certain DLL file missing from your Windows install.

You can grab [this tiny C++ redistributable from Microsoft](https://www.microsoft.com/en-us/download/details.aspx?id=29) to get the missing DLL.  Let me know if that gets you anywhere.

**Comment by pastorhudson** [comment]
I'm getting the same error, and this link is dead. Thanks Microsoft. . .
