### ISSUE TITLE
Error registering and then reopening screenbloom

### ISSUE THREAD

**Issue by Malaga82** [kershner/screenBloom#58]
Hello,
i launched screenbloom and i tried to register.
The spin loading never ended but i have a generated screenBloom_config.cfg .
After that i exited and launched again screenbloom but i have this error everytime.
Is there a way to have screenbloom working fine or am i missing something?
I read about antivirus, i have windows defender and already whitelistened both process and folder.
I have w10 latest version( 1709 ).
Thanks for a reply
![2017-12-13](https://user-images.githubusercontent.com/3518802/33950124-d6899164-e02b-11e7-9787-6a5982efb509.png)

**Comment by kershner** [comment]
Hey there!  Sorry for this late response.

I think this is some kind of unicode error, maybe something to do with a character in one of your Hue lights' names.  Just a guess.  If you could link or attach or send me your config file I might be able to get some clues.

**Comment by Malaga82** [comment]
Hello,
thanks for the reply.
The problem is related with lights, for a strange reason sometimes the hub coudln't control them and made this error.
I upgraded the firmware for both hub and leds and now it works as indeed.
:)
