### ISSUE TITLE
Random lights turn on

### ISSUE THREAD

**Issue by Reaping666** [kershner/screenBloom#65]
Hi,
so far I'm loving screenBloom. It works quite well for what I want to achieve.

But I noticed that if screenBloom is running, sometimes lights in other rooms turn on. This does not happen if my PC isn't running or I have screenBloom turned off. I also removed all routines in other apps to check only against screenBloom, it still does happen if screenBloom is active.
Is there something I can do to reduce/stop this behavior?

Thanks in advance.

**Comment by kershner** [comment]
Hi there!

There really isn't any way for ScreenBloom to address lights that you haven't told it to address.  One possible thing I can think of (because it's happened to me!) is that maybe you've moved lights around and haven't updated the ScreenBloom config?

**Comment by Reaping666** [comment]
What helped on my side was pushing the update buffer from 0.0 to 0.1. Might be just the bridge doing crazy stuff ^^

**Comment by kershner** [comment]
That's great, going to close this for now.  Feel free to let me know if the issue happens again!
