### ISSUE TITLE
Request: Command line for Task Organizer

### ISSUE THREAD

**Issue by qserror** [kershner/screenBloom#69]
Hello Kershner! at first thank you for this nice app!  (which i would give a donation in the next days!)

i start screenbloom with the taskorganizer and i want to know if there is a "start" argument? 

![grafik](https://user-images.githubusercontent.com/35936407/35532703-6d37b31e-053b-11e8-9362-c109bd52ec5e.png)

![grafik](https://user-images.githubusercontent.com/35936407/35532727-8989eadc-053b-11e8-8615-6d740ab197e8.png)

best regards

qserror

**Comment by kershner** [comment]
Hey there!

There is command line support, but it's very limited at the moment.  See [the readme here](https://github.com/kershner/screenBloom#command-line-args-windows-version).

Currently I don't think your exact use case is supported, BUT, I think you can effectively get what you want by saving a preset with the **Auto Start** option enabled.  That way when you start screenBloom.exe, and your 'Auto Start' preset was the last one used, ScreenBloom will automatically start running/syncing the lights etc.  You can combine this with the `-q` argument and you can launch it from Task Organizer without the web browser interface coming up.

I think that should effectively get you what you want to do.  Let me know if you have any questions.

**Comment by qserror** [comment]
Hey Kershner

It works perfectly! Thanks a lot. You're a hero !!! 

Best regards qserror
