### ISSUE TITLE
Config Option to start ScreenBloom Thread on app start

### ISSUE THREAD

**Issue by popy2k14** [kershner/screenBloom#7]
Hey Tyler,

would be a nice addition to add a config parameter to start the ScreenBloom Thread at startup of the app.

Ill want to use ScreenBloom on my HTPC and every time i boot it, ill have to press start on the webinterface. The WAF here is very low :-)

what do you think about this request?

thx
Tobias

**Comment by kershner** [comment]
Hey Tobias,

Yeah this is a good idea and I know others have requested it.  Should be pretty straightforward to implement.  I've put it on my list for the next release.  ScreenBloom will let you know automatically when a new version is available to download so be on the lookout for that.  I'll keep this issue open until then.

Thanks for reaching out!

**Comment by popy2k14** [comment]
Thx for planing to implement the feature.

Tobias

**Comment by kershner** [comment]
Closing as the feature has been added.  Great idea.
