### ISSUE TITLE
I'm getting this error on startup =(

### ISSUE THREAD

**Issue by merket** [kershner/screenBloom#71]
![screenbloom](https://user-images.githubusercontent.com/20828278/36010280-acff23aa-0d61-11e8-8467-3b45083d3880.jpg)

**Comment by duk6046** [comment]
me too

**Comment by kershner** [comment]
Hey there guys -

I think this error is indicating that something has changed in your Hue bridge lighting config that doesn't match what the ScreenBloom config has.  If you just delete your config and re-sync with your bridge everything might be fine.

The config file is located at:
`c:/Users/<Username>/AppData*/Roaming/screenBloom/`
*You'll need to enable 'Show Hidden Files' to see this directory.

Let me know if that ends up solving the issue!

**Comment by duk6046** [comment]
thanks, work again
