### ISSUE TITLE
Config Option to prevent the webbrowser opening on app start

### ISSUE THREAD

**Issue by popy2k14** [kershner/screenBloom#8]
Once again Tyler,

would be a nice addition to add a config parameter to prevent the webbrowser from opening the screenbloom webinterface on app start.

Ill want to use ScreenBloom on my HTPC and every time i boot it (with screenbloom in autostart) chrome opens.

what do you think about this request?

thx
Tobias

**Comment by kershner** [comment]
Another straightforward and good idea, I'll investigate this as well.

Thanks again for the feedback!

**Comment by popy2k14** [comment]
Thx for planing to implement the feature.

Tobias

**Comment by SimplyMinimal** [comment]
I also wanted this feature.

Work in progress:

#16

**Comment by kershner** [comment]
Just merged it in, will be part of the next release.  Great work SimplyMinimal!
