### ISSUE TITLE
After installing ScreenBloom, other apps cannot find Philips Hue

### ISSUE THREAD

**Issue by JadeFalken** [kershner/screenBloom#84]
As the header states, after I had installed ScreenBloom no pc app will communicate with Hue, the only one that seems to work is my android app, which still will give up every now and again and randomly let screen bloom take over. (Not so exciting when randomly in the middle of the night my lights come on full blast)

**Comment by kershner** [comment]
Hey there!

The way ScreenBloom works is by rapidly sending commands to the selected bulbs to update their color/brightness.  It will continue to send those commands as long as it's running.  So if you've got ScreenBloom actively running on a light, change that light with your app, your changes will be quickly overwritten by the next update from ScreenBloom, which is likely only miliseconds later.

So the answer I think is to simply make sure ScreenBloom is "stopped" before you want to use other apps on those particular lights.

Let me know if that's not quite the issue!

**Comment by JadeFalken** [comment]
Turns out, I had a routine set up by default that would turn the lights on. I normally wouldn't see this as my Razer chroma is normally in control. 

Also I originally had my hue bridge hooked up to my pc via shared internet connection. Connecting it to a router let's other apps take over from screen bloom.

**Comment by kershner** [comment]
Awesome, glad to hear you've resolved it!  Let me know if you run into any other issues.
