### ISSUE TITLE
Could you fix your website and make proper releases?

### ISSUE THREAD

**Issue by max-scopp** [kershner/screenBloom#88]
Tried to download today. Doesn't work, nor any alternative version.

![image](https://user-images.githubusercontent.com/11851540/49892030-43006580-fe48-11e8-8d48-a4b81fd6f7a5.png)

I told myself "fine, at least it's open source, GitHub's cdn is more trustworthy anyways."
Turns out you don't even make releases.

Let me tell you, I'm lazypants too, but it's ages since I did something with python.
Take it as a note, maybe I find the patience to bundle it up myself.

Best of wishes. No Biggy.

**Comment by kershner** [comment]
Hey, thanks so much for raising this issue!  It's all fixed now.

I've recently migrated my old domain and I guess I forgot the ScreenBloom files were still hosted there, can't tell you enough how much I appreciate you letting me know!

I will definitely look at using GitHub releases, that's a great idea.
