### ISSUE TITLE
2 questions

### ISSUE THREAD

**Issue by avogabo** [kershner/screenBloom#89]
1-  can you explain me how to ScreenBloom can be launched with command line arguments?
2- its possible that when close ScreenBloom turn lights off?

**Comment by kershner** [comment]
Hey there!  The command line args are still limited to just quiet mode on Windows, haven't had time to expand it unfortunately.

[Here's the link ](https://github.com/kershner/screenBloom#command-line-args-windows-version) to the relevant section of the readme.
If anyone is interested in adding such support I think you'd poke around [here ](https://github.com/kershner/screenBloom/blob/master/app/screenbloom.py#L450)and [here](https://github.com/kershner/screenBloom/blob/master/app/modules/startup.py#L87).

Turning the lights off when ScreenBloom is stopped is not currently supported, but would be simple to add via the Hue API.  You could easily just drop in a call [here](https://github.com/kershner/screenBloom/blob/master/app/modules/view_logic.py#L85).
