### ISSUE TITLE
Screen Zone problem 

### ISSUE THREAD

**Issue by qserror** [kershner/screenBloom#97]
Hello Kershner!

i have the same issue like an older post here: https://github.com/kershner/screenBloom/issues/33
before i reinstall win10 it works great. after reinstalling it, i do all the steps needed... i reconnect the hue bridge, make the zones, create a silent task etc... trying to reinstall and delete all folders doesnt bring the solution either :'/ 

FYI: the party mode works fine -.-"
FYI 2: the application has adminstration right activated
FYI 3: in my firewall is screenbloom.exe completely open 

[Uploading config_screenbloomXXX.zip…]()

**Comment by millskyle** [comment]
After a lot of experimenting, I figured out a common theme:  if **any** of the zones have either dimension as a single unit, none of the zones function and the lights freeze.  e.g. 1x2 doesn't work, 3x1 doesn't work, but 2x3 works fine.

**Comment by qserror** [comment]
It works for me! THANK YOU A LOT!!!
